# Generated by Django 5.1.7 on 2025-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parkplatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('kapazitaet', models.IntegerField()),
                ('preis_pro_stunde', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
