# Generated by Django 5.1.7 on 2025-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkplatz',
            name='bewertung',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='frei',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='verfuegbar',
            field=models.BooleanField(default=True),
        ),
    ]
