# Generated by Django 5.1.7 on 2025-04-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0002_parkplatz_bewertung_parkplatz_frei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkplatz',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='letztes_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='oeffnungszeiten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='schliesszeiten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parkplatz',
            name='frei',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
