# Generated by Django 5.1.7 on 2025-04-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0004_benutzerprofil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stadt', models.CharField(blank=True, max_length=100, null=True)),
                ('liga', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parkplatz',
            name='frei',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadien', to='parkmanagement.verein')),
            ],
        ),
    ]
