# Generated by Django 5.1.7 on 2025-04-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0005_verein_alter_parkplatz_frei_stadion'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkplatz',
            name='stadion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkplaetze', to='parkmanagement.stadion'),
        ),
    ]
