# Generated by Django 5.1.7 on 2025-04-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0006_parkplatz_stadion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benutzerprofil',
            name='lieblingsverein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='parkmanagement.verein'),
        ),
    ]
