# Generated by Django 5.1.7 on 2025-04-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0007_alter_benutzerprofil_lieblingsverein'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_adresse', models.CharField(max_length=255)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('strecke_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dauer_minuten', models.IntegerField(blank=True, null=True)),
                ('transportmittel', models.CharField(choices=[('auto', 'Auto'), ('bus', 'Bus'), ('bahn', 'Bahn'), ('zu_fuss', 'zu Fuß')], default='auto', max_length=50)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('route_url', models.URLField(blank=True, null=True)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routen', to=settings.AUTH_USER_MODEL)),
                ('parkplatz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routen', to='parkmanagement.parkplatz')),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routen', to='parkmanagement.stadion')),
            ],
        ),
    ]
