# Generated by Django 5.1.7 on 2025-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0008_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkplatz',
            name='kapazitaet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkplatz',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkplatz',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkplatz',
            name='preis_pro_stunde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
