# Generated by Django 5.1.7 on 2025-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0009_alter_parkplatz_kapazitaet_alter_parkplatz_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadion',
            name='bild_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
