# Generated by Django 5.1.7 on 2025-07-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0010_stadion_bild_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkplatz',
            options={'verbose_name': 'Parkplatz', 'verbose_name_plural': 'Parkplätze'},
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='external_id',
            field=models.CharField(blank=True, help_text='Externe ID von API-Anbietern', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='live_data_json',
            field=models.JSONField(default=dict, help_text='Live-Verfügbarkeitsdaten von externen APIs im JSON-Format'),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='live_data_source',
            field=models.CharField(blank=True, help_text='Quelle der Live-Daten', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parkplatz',
            name='live_data_update',
            field=models.DateTimeField(blank=True, help_text='Zeitstempel der letzten Live-Daten Aktualisierung', null=True),
        ),
    ]
