# Generated by Django 5.1.7 on 2025-07-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0012_alter_parkplatz_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkplatz',
            name='live_data_json',
            field=models.JSONField(default=dict, help_text='Live-Verfügbarkeitsdaten von externen APIs im JSON-Format', null=True),
        ),
    ]
