# Generated by Django 5.1.7 on 2025-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkmanagement', '0013_alter_parkplatz_live_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkplatz',
            name='live_data_json',
            field=models.JSONField(blank=True, default=dict, help_text='Live-Verfügbarkeitsdaten von externen APIs im JSON-Format', null=True),
        ),
    ]
